//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Holds the Brand data as a class from the DB.
    /// </summary>
    public partial class automarkak
    {
        /// <summary>
        /// Gets or Sets the ID.
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Gets or Sets the name.
        /// </summary>
        public string nev { get; set; }
        /// <summary>
        /// Gets or Sets the country name.
        /// </summary>
        public string orszagnev { get; set; }
        /// <summary>
        /// Gets or Sets the URL.
        /// </summary>
        public string url { get; set; }
        /// <summary>
        /// Gets or Sets the foundation date.
        /// </summary>
        public Nullable<int> alapitaseve { get; set; }
        /// <summary>
        /// Gets or Sets the annual traffic.
        /// </summary>
        public Nullable<int> evesforgalom { get; set; }
    }
}
