//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    /// <summary>
    /// Handles the tables for the database.
    /// </summary>
    public partial class carshopdatabaseEntities1 : DbContext
    {
        /// <summary>
        /// Creates the DB instance.
        /// </summary>
        public carshopdatabaseEntities1()
            : base("name=carshopdatabaseEntities1")
        {
        }
    
        /// <summary>
        /// Handles the model creation inside the tables.
        /// </summary>
        /// <param name="modelBuilder">The builder.</param>
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        /// <summary>
        /// Gets or Sets the brand table.
        /// </summary>
        public virtual DbSet<automarkak> automarkak { get; set; }
        /// <summary>
        /// Gets or Sets the extra table.
        /// </summary>
        public virtual DbSet<extrak> extrak { get; set; }
        /// <summary>
        /// Gets or Sets the Car table.
        /// </summary>
        public virtual DbSet<modellek> modellek { get; set; }
        /// <summary>
        /// Gets or Sets the switch table.
        /// </summary>
        public virtual DbSet<modellextrakapcsolo> modellextrakapcsolo { get; set; }
    }
}
