//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Holds the extra data as a class from the DB.
    /// </summary>
    public partial class extrak
    {
        /// <summary>
        /// Gets or Sets the ID.
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Gets or Sets the category name.
        /// </summary>
        public string kategorianev { get; set; }
        /// <summary>
        /// Gets or Sets the name.
        /// </summary>
        public string nev { get; set; }
        /// <summary>
        /// Gets or Sets the price.
        /// </summary>
        public Nullable<int> ar { get; set; }
        /// <summary>
        /// Gets or Sets the color.
        /// </summary>
        public string szin { get; set; }
        /// <summary>
        /// Gets or Sets the 'can be used more times' property.
        /// </summary>
        public Nullable<byte> tobbszor_hasznalhato { get; set; }
    }
}
