//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class modellextrakapcsolo1
    {
        public int Id { get; set; }
        public Nullable<int> modellid { get; set; }
        public Nullable<int> extraid { get; set; }
    }
}
