//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;

    /// <summary>
    /// Holds the Switch data as a class from the DB.
    /// </summary>
    public partial class modellextrakapcsolo
    {
        /// <summary>
        /// Gets or Sets the ID.
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Gets or Sets the modelid key.
        /// </summary>
        public Nullable<int> modellid { get; set; }
        /// <summary>
        /// Gets or Sets the extraid value.
        /// </summary>
        public Nullable<int> extraid { get; set; }
    }
}
