//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Holds the Car data as a class from the DB.
    /// </summary>
    public partial class modellek
    {
        /// <summary>
        /// Gets or Sets the ID.
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Gets or Sets the brand ID of the car.
        /// </summary>
        public Nullable<int> marka_id { get; set; }
        /// <summary>
        /// Gets or Sets the name of the car.
        /// </summary>
        public string nev { get; set; }
        /// <summary>
        /// Gets or Sets the foundation date of the car.
        /// </summary>
        public Nullable<System.DateTime> megjelenesnapja { get; set; }
        /// <summary>
        /// Gets or Sets the engine volume.
        /// </summary>
        public Nullable<int> motorterfogat { get; set; }
        /// <summary>
        /// Gets or Sets the horse power.
        /// </summary>
        public Nullable<int> loero { get; set; }
        /// <summary>
        /// Gets or Sets the base price.
        /// </summary>
        public Nullable<int> alapar { get; set; }
    }
}
